version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgre_database
    restart: always
    environment:
      POSTGRES_USER: fullstack_app
      POSTGRES_PASSWORD: fullstack_app_password
      POSTGRES_DB: fullstack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend-Node
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      # NOTE:
      # These environment variables (e.g. JWT_SECRET, MIDTRANS_SERVER_KEY) are exposed here
      # only for development/demo purposes as part of this technical test.
      # In a real production environment, these values should be secured using .env files
      # (excluded from version control), secret managers, or deployment-specific env vars.
      DATABASE_URL: postgresql://fullstack_app:fullstack_app_password@postgres:5432/fullstack_db
      BASE_URL: http://localhost:3001/uploads
      FRONTEND_URL: http://frontend_service:3000
      MIDTRANS_SERVER_KEY: SB-Mid-server-_8WTj0iDrj0Y4LTs5NCmPm8x
      JWT_SECRET: IMa8ewEWBnaocxXgknNaehpAkl59HORQ5gJZvJW9d3iPc79UFwOdDK7HelVzBSCu
    depends_on:
      - postgres
    volumes:
      - ./Backend-Node/src/product/uploads:/app/src/product/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_HOST_API: http://backend_service:3001

volumes:
  postgres_data:
