version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgre_database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend-Node
      dockerfile: Dockerfile
    container_name: backend_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      BASE_URL: http://localhost:3001/uploads
    depends_on:
      - postgres
    volumes:
      - ./Backend-Node/src/product/uploads:/app/src/product/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
